apiVersion: apps/v1
kind: Deployment

metadata:
    name: mycustomcpp
spec:
    replicas: 1
    selector:
      matchLabels:
        app:  mycustomcpp
    template:
      metadata:
        labels:
          app:  mycustomcpp
      spec:
        containers:
        - image: public.ecr.aws/u3j4v3u4/myapp
          imagePullPolicy:  Always
          name: myapp
          ports:
          - containerPort: 4040


